server:
  port: 8763

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
      
eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


ribbon:
  eureka:
    enabled: true
    
logging:
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'
    
    